import type { FundTechnicals } from "./amfiClient";
export type ScoringWeights={strategicWeight:number;opportunityWeight:number};
export type IndexData={name:string;pChange:number;last:number;previousClose:number;yearHigh:number;yearLow:number};
export type FundInput={id:number;name:string;proxyIndex:string;category:string;technicals:FundTechnicals};
export type FundScore={fundId:number;fundName:string;proxyIndex:string;category:string;strategicScore:number;opportunityScore:number;finalScore:number;dipOpportunityScore:number;sectorMove:number|null;sectorProxy:string;sectorExposure:"DIRECT"|"THEMATIC"|"BROAD";dipSignal:"HIGH"|"MEDIUM"|"LOW"|"NONE";scoreBand:"Strong"|"Good"|"Watch"|"Weak";indexMove:number|null;trendStatus:"uptrend"|"downtrend"|"sideways";actionLabel:"BUY ON DIP"|"SIP"|"WAIT"|"AVOID";classification:"Healthy Correction"|"Structural Breakdown"|"Neutral";reason:string;technicals:FundTechnicals;isAvoid:boolean};
const clamp=(v:number)=>Math.max(0,Math.min(100,v));
function trendComponent(t:FundTechnicals["trendStatus"]){return t==="uptrend"?76:t==="sideways"?54:24;}
function returnsComponent(t:FundTechnicals){const a=[[t.return1M,.15],[t.return3M,.25],[t.return6M,.25],[t.return1Y,.35]] as const;let s=0,w=0;for(const[v,x]of a)if(v!=null&&Number.isFinite(v)){s+=v*x;w+=x;}return w?clamp(50+s/w*2.2):50;}
function drawdownQualityComponent(d:number|null){if(d==null||!Number.isFinite(d))return 50;if(d>=-5)return 68;if(d>=-10)return 64;if(d>=-20)return 58;if(d>=-30)return 47;if(d>=-40)return 37;return 28;}
function relativeStrengthComponent(v:number|null){if(v==null||!Number.isFinite(v))return 50;if(v>8)return 82;if(v>5)return 74;if(v>2)return 67;if(v>0)return 60;if(v>-3)return 50;if(v>-7)return 41;return 32;}
export function computeStrategicScore(t:FundTechnicals,rs:number|null){return clamp(trendComponent(t.trendStatus)*.30+returnsComponent(t)*.30+drawdownQualityComponent(t.drawdown52W)*.15+relativeStrengthComponent(rs)*.25);}
function dipComponent(m:number|null){if(m==null||!Number.isFinite(m))return 50;if(m<=-3)return 95;if(m<=-2)return 88;if(m<=-1.5)return 82;if(m<=-1)return 76;if(m<=-.5)return 64;if(m<=-.25)return 57;if(m<=0)return 50;if(m<=1)return 43;if(m<=2)return 35;return 28;}
function drawdownOpportunityComponent(d:number|null){if(d==null||!Number.isFinite(d))return 50;if(d<=-30)return 94;if(d<=-20)return 84;if(d<=-15)return 76;if(d<=-10)return 68;if(d<=-5)return 57;return 45;}
function momentumComponent(v:number|null){if(v==null||!Number.isFinite(v))return 50;if(v<=-8)return 82;if(v<=-5)return 75;if(v<=-2)return 65;if(v<=2)return 54;if(v<=5)return 44;return 34;}
function trendConfirmationComponent(t:FundTechnicals["trendStatus"]){return t==="uptrend"?72:t==="sideways"?50:22;}
export function computeOpportunityScore(t:FundTechnicals,m:number|null){return clamp(dipComponent(m)*.35+drawdownOpportunityComponent(t.drawdown52W)*.30+momentumComponent(t.momentum10D)*.20+trendConfirmationComponent(t.trendStatus)*.15);}
export function scoreBand(s:number):"Strong"|"Good"|"Watch"|"Weak"{return s>=80?"Strong":s>=65?"Good":s>=50?"Watch":"Weak";}
function calibrateOverallScore(raw:number,strategic:number,opportunity:number){return clamp(50+(raw-50)*1.22+(strategic-50)*.12+(opportunity-50)*.08);}
type Exposure={proxies:string[];label:string;kind:"DIRECT"|"THEMATIC"|"BROAD"};
function exposureForFund(f:FundInput):Exposure{const text=`${f.name} ${f.category} ${f.proxyIndex}`.toUpperCase();if(text.includes("DIGITAL")||text.includes(" IT")||text.includes("NIFTY IT"))return{proxies:["NIFTY IT"],label:"NIFTY IT",kind:"DIRECT"};if(text.includes("BFSI")||text.includes("BANKING")||text.includes("FINANCIAL SERVICES"))return{proxies:["NIFTY PSU BANK","NIFTY FINANCIAL SERVICES","NIFTY BANK"],label:"NIFTY PSU BANK / FINANCIALS",kind:"DIRECT"};if(text.includes("HEALTHCARE")||text.includes("HEALTH"))return{proxies:["NIFTY HEALTHCARE","NIFTY PHARMA"],label:"NIFTY HEALTHCARE",kind:"DIRECT"};if(text.includes("INFRA"))return{proxies:["NIFTY INFRASTRUCTURE"],label:"NIFTY INFRASTRUCTURE",kind:"DIRECT"};if(text.includes("SERVICES"))return{proxies:["NIFTY SERVICES SECTOR","NIFTY FINANCIAL SERVICES"],label:"NIFTY SERVICES SECTOR",kind:"THEMATIC"};if(text.includes("SMALL CAP")||text.includes("SMALLCAP"))return{proxies:["NIFTY SMALLCAP 250"],label:"NIFTY SMALLCAP 250",kind:"DIRECT"};if(text.includes("MID CAP")||text.includes("MIDCAP"))return{proxies:["NIFTY MIDCAP 150"],label:"NIFTY MIDCAP 150",kind:"DIRECT"};if(text.includes("NEXT 50")||text.includes("NEXT50"))return{proxies:["NIFTY NEXT 50"],label:"NIFTY NEXT 50",kind:"DIRECT"};if(text.includes("GOLD"))return{proxies:["GOLD"],label:"GOLD",kind:"DIRECT"};if(f.proxyIndex.toUpperCase()!=="NIFTY 500"&&f.proxyIndex.toUpperCase()!=="NIFTY 50")return{proxies:[f.proxyIndex],label:f.proxyIndex,kind:"THEMATIC"};return{proxies:[f.proxyIndex],label:f.proxyIndex,kind:"BROAD"};}
function relevantSectorMove(map:Map<string,IndexData>,e:Exposure){const moves=e.proxies.map(p=>map.get(p.toUpperCase())?.pChange).filter((v):v is number=>v!=null&&Number.isFinite(v));return moves.length?Math.min(...moves):null;}
function computeDipOpportunityScore(strategic:number,t:FundTechnicals,sectorMove:number|null,e:Exposure){let s=dipComponent(sectorMove)*.50+strategic*.25+drawdownOpportunityComponent(t.drawdown52W)*.15+trendConfirmationComponent(t.trendStatus)*.10;if(e.kind==="DIRECT"&&sectorMove!=null&&sectorMove<=-.75)s+=7;if(e.kind==="DIRECT"&&sectorMove!=null&&sectorMove<=-1.5)s+=4;if(t.trendStatus==="downtrend")s-=25;return Math.round(clamp(s));}
export function scoreFunds(funds:FundInput[],indices:IndexData[],weights:ScoringWeights):FundScore[]{const map=new Map<string,IndexData>();for(const i of indices)map.set(i.name.toUpperCase(),i);const n50=map.get("NIFTY 50")?.pChange??null;return funds.map(f=>{const t=f.technicals;const indexMove=map.get(f.proxyIndex.toUpperCase())?.pChange??n50;const exposure=exposureForFund(f);const sectorMove=relevantSectorMove(map,exposure);const rs=t.momentum50D!=null&&n50!=null?t.momentum50D-n50*10:null;const strategicScore=computeStrategicScore(t,rs);const opportunityScore=computeOpportunityScore(t,indexMove);const raw=clamp(strategicScore*weights.strategicWeight+opportunityScore*weights.opportunityWeight);const baseFinal=calibrateOverallScore(raw,strategicScore,opportunityScore);const dipOpportunityScore=computeDipOpportunityScore(strategicScore,t,sectorMove,exposure);
  // Overall remains quality + opportunity, but a real sector correction gets a tactical overlay.
  // This is what makes a high-quality IT/BFSI fund rise when its concerned sector is actually falling.
  const tacticalOverlay=sectorMove!=null&&sectorMove<=-.75&&exposure.kind!=="BROAD"?baseFinal+(dipOpportunityScore-baseFinal)*.90:baseFinal;
  const finalScore=Math.round(clamp(tacticalOverlay));const band=scoreBand(finalScore);
  const dipSignal:FundScore["dipSignal"]=sectorMove!=null&&sectorMove<=-1.5&&dipOpportunityScore>=65&&t.trendStatus!=="downtrend"?"HIGH":sectorMove!=null&&sectorMove<=-.5&&dipOpportunityScore>=58&&t.trendStatus!=="downtrend"?"MEDIUM":sectorMove!=null&&sectorMove<0?"LOW":"NONE";
  let isAvoid=false;let classification:FundScore["classification"]="Neutral";let actionLabel:FundScore["actionLabel"]="SIP";let reason="";
  if(t.trendStatus==="downtrend"){isAvoid=true;classification="Structural Breakdown";actionLabel="AVOID";reason=`Fund below 50D & 200D SMA — structural downtrend.${t.drawdown52W!=null?` 52W drawdown: ${t.drawdown52W.toFixed(1)}%`:""}`;}
  else if(sectorMove!=null&&sectorMove<=-1&&exposure.kind==="DIRECT"&&strategicScore>=55){classification="Healthy Correction";actionLabel="BUY ON DIP";reason=`${exposure.label} is down ${sectorMove.toFixed(2)}% today. Direct sector exposure + healthy fund trend. High-quality sector correction opportunity for staggered accumulation.`;}
  else if(indexMove!=null&&indexMove<-1.5&&t.trendStatus==="uptrend"){classification="Healthy Correction";actionLabel="BUY ON DIP";reason=`${f.proxyIndex} down ${indexMove.toFixed(2)}% today while trend remains intact. Potential accumulation window.`;}
  else if(sectorMove!=null&&sectorMove<-.5){classification="Healthy Correction";actionLabel="SIP";reason=`${exposure.label} is correcting ${sectorMove.toFixed(2)}% today. Suitable for staggered deployment if the fund trend remains healthy.`;}
  else if(band==="Weak"){actionLabel="WAIT";reason="Overall score is weak. Wait for stronger trend or better correction confirmation.";}
  else{actionLabel="SIP";reason="Market stable. Prefer regular SIP over chasing the move.";}
  if(!isAvoid&&t.trendStatus==="sideways"&&t.momentum20D!=null&&t.momentum20D<-5){actionLabel="WAIT";reason=`Sideways trend with negative 20D momentum (${t.momentum20D.toFixed(1)}%). Wait for confirmation.`;}
  return{fundId:f.id,fundName:f.name,proxyIndex:f.proxyIndex,category:f.category,strategicScore:Math.round(strategicScore),opportunityScore:Math.round(opportunityScore),finalScore,dipOpportunityScore,sectorMove,sectorProxy:exposure.label,sectorExposure:exposure.kind,dipSignal,scoreBand:band,indexMove,trendStatus:t.trendStatus,actionLabel,classification,reason,technicals:t,isAvoid};});}
export type MarketRegime={label:"RISK ON"|"RISK OFF"|"NEUTRAL";breadthPercent:number;strategyNote:string;color:"green"|"red"|"yellow"};
export function computeMarketRegime(indices:IndexData[]):MarketRegime{if(!indices.length)return{label:"NEUTRAL",breadthPercent:50,strategyNote:"Market data unavailable. Maintain regular SIP.",color:"yellow"};const breadthPercent=Math.round(indices.filter(i=>i.pChange>0).length/indices.length*100);const n=indices.find(i=>i.name.toUpperCase()==="NIFTY 50");const m=indices.find(i=>i.name.toUpperCase().includes("MIDCAP 150"));const s=indices.find(i=>i.name.toUpperCase().includes("SMALLCAP"));const broadNeg=(n?.pChange??0)<-1&&(m?.pChange??0)<-1&&(s?.pChange??0)<-1;const broadPos=(n?.pChange??0)>.5&&breadthPercent>60;if(broadNeg||breadthPercent<35)return{label:"RISK OFF",breadthPercent,strategyNote:"Broad market weakness. Continue core SIP, but prioritize high-quality funds whose concerned sector is under a healthy correction.",color:"red"};if(broadPos||breadthPercent>65)return{label:"RISK ON",breadthPercent,strategyNote:"Markets trending up. Continue SIP + deploy corrections selectively.",color:"green"};return{label:"NEUTRAL",breadthPercent,strategyNote:"Mixed market signals. Use sector-specific corrections for tactical deployment.",color:"yellow"};}
